openapi: 3.0.0
info:
  version: 1.0.0
  title: AMS Modeles API
  description: "AMS Modeles API: "
  license:
    name: NIQ
    url: 'https://www.brandbank.com/content-licensing/'

servers:
  - url: http://amsairflowserver-usdev.azure-modelplat-np.nielsencsp.net/api/v1/dags
    description: AMS Dev Server
  - url: http://amsairflowserver-usuat.azure-modelplat-np.nielsencsp.net/api/v1/dags
    description: AMS UAT Server
  - url: http://amsairflowserver-usprod.azure-modelplat-p.nielsencsp.net/api/v1/dags
    description: AMS PROD Server

security:
  - BasicAuth: []

tags:
 - name: BDL AMS SAS LOAD  
   description: 'BDL AMS SAS LOAD '
   externalDocs:
     description: 'BDL AMS SAS LOAD'
     url: ''
 - name: CS AMS AGG  
   description: 'CS AMS AGG '
   externalDocs:
     description: 'CS AMS AGG'
     url: ''  
 - name: CS AMS AID
   description: 'Automated Item Definition is all about creating items after grouping products which share similar characteristics. Once we identify the similar kind of products we run some dedicated algorithms for those products and group them to a group and assign flag(good, bad, issue, no data) to those group. (In short we call those groups as Item)'
   externalDocs:
     description: 'CS AMS AID'
     url: ''  
 - name: CS AMS AUTOSCALE
   description: 'CS AMS AUTOSCALE'
   externalDocs:
     description: 'testing the code'
     url: ''
 - name: CS AMS CENSUS STORES
   description: 'CS AMS CENSUS STORES'
   externalDocs:
     description: 'CS AMS CENSUS STORES'
     url: ''
 - name: CS AMS CUSTOM WEEKLY REFRESH
   description: 'CS AMS CUSTOM WEEKLY REFRESH'
   externalDocs:
     description: 'CS AMS CUSTOM WEEKLY REFRESH'
     url: ''  
 - name: CS AMS EDA MODEL  
   description: 'CS AMS EDA MODEL'
   externalDocs:
     description: 'testing the code'
     url: ''  
 - name: EDA MODEL PARALLEL SPLITS
   description: 'EDA MODEL PARALLEL SPLITS'
   externalDocs:
     description: 'CS AMS EDA MODEL '
     url: ''
 - name: CS AMS ITEM SUMMARY  
   description: 'CS AMS ITEM SUMMARY  '
   externalDocs:
     description: 'CS AMS ITEM SUMMARY'
     url: ''  
 - name: CS AMS ITEMAGG
   description: 'ItemAgg is all about creating group items and split into different groups , which share similar advantages. \nEfficient management of large order volumes, Better visibility on production and Optimization of your preparation times.'
   externalDocs:
     description: 'testing the code'
     url: ''  
 - name: CS AMS MID
   description: 'Initially – we include all of the product_ids that cover the scope identified in the Artemis order. Initially – we include all of the product_ids that cover the scope identified in the Artemis order.  To limit our data we are creating those ids mainly for reducing the number of product_id (ups). The main aim creating MID to club the similar kind of product_id on predefined rules. So that we modeling only product_id which are relevant . we call it MIDs ((Modeling IDs)'
   externalDocs:
     description: 'testing the code'
     url: ''  
 - name: CS AMS NONAGG
   description: 'CS AMS NONAGG'
   externalDocs:
     description: 'No-Filter Scenario'
     url: ''  
 - name: CS AMS POS SUMMARY  
   description: 'CS AMS POS SUMMARY  '
   externalDocs:
     description: 'testing the code'
     url: ''
 - name: CS AMS PRICE THRESHOLDS MODEL  
   description: 'CS AMS PRICE THRESHOLDS MODEL '
   externalDocs:
     description: 'testing the code'
     url: '' 
 - name: AID
   description: 'AID'
   externalDocs:
     description: 'testing the code'
     url: ''  
 - name: CS AMS PRODSIM
   description: 'Prodsim is to find similarity between the products. We compare a set of products with an another set of products in order to find out the similarity.'
   externalDocs:
     description: 'testing the code'
     url: ''  
 - name: CS AMS REGULARPRICE  
   description: 'CS AMS REGULARPRICE '
   externalDocs:
     description: 'testing the code'
     url: ''
 - name: Rudimentary Model Functionalities
   description: 'Rudimentary Model Functionalities'
   externalDocs:
     description: 'testing the code'
     url: ''  
 - name: CS AMS STOREAGG
   description: 'CS AMS STOREAGG'
   externalDocs:
     description: 'testing the code'
     url: ''  
 - name: FAIL JOB
   description: 'FAIL JOB'
   externalDocs:
     description: 'testing the code'
     url: ''  
 - name: MASTER DUMMY
   description: 'MASTER DUMMY'
   externalDocs:
     description: 'testing the code'
     url: ''  
 - name: MASTER DUMMY PYTHON  
   description: 'MASTER DUMMY PYTHON  '
   externalDocs:
     description: 'testing the code'
     url: ''
 - name: SUBMIT JOB
   description: 'SUBMIT JOB'
   externalDocs:
     description: 'testing the code'
     url: ''  
 - name: SUBMIT JOB PYTHON
   description: 'SUBMIT JOB PYTHON'
   externalDocs:
     description: 'testing the code'
     url: ''  
 - name: SUBMIT JOB QA AS
   description: 'SUBMIT JOB QA AS'
   externalDocs:
     description: 'testing the code'
     url: ''

   
paths:
  # MASTER DUMMY post dag
  /MASTER_DUMMY/dagRuns:
    post:
      summary: Trigger US-STOREAGG dag.Change
      operationId: MASTER_DUMMY
      tags:
        - MASTER DUMMY
      requestBody:
        required: true
        content:
          application/json:
            schema:
              #  ----- Added schema  ------------------------------------
              $ref: '#/components/schemas/AMS_Shema_MASTER_DUMMY'
      responses:
        '200':
          #  ----- Added code 200  ----------------------------------------
          $ref: '#/components/responses/200Success'
        '400':
          #  ----- Added error 400  ----------------------------------------
          $ref: '#/components/responses/400Error'
   
          
   
# BDL_AMS_SAS_LOAD
  /BDL_AMS_SAS_LOAD/dagRuns:
    post:
      summary: 'Add Summary Here'
      operationId: BDL_AMS_SAS_LOAD
      tags:
        - BDL AMS SAS LOAD
      requestBody:
        required: true
        content:
          application/json:
            schema:
              #  ----- Added schema  ------------------------------------
              $ref: '#/components/schemas/TO_DO_Shema'
      responses:
        '200':
          #  ----- Added code 200  ----------------------------------------
          description: Successfully created a new artist
        '400':
          #  ----- Added error 400  ----------------------------------------
          $ref: '#/components/responses/400Error'
   


# CS_AMS_AGG
  /CS_AMS_AGG/dagRuns:
    post:
      summary: 'Aggregated Extracts'
      operationId: CS_AMS_AGG
      tags:
        - CS AMS AGG
      requestBody:
        required: true
        content:
          application/json:
            schema:
              #  ----- Added schema  ------------------------------------
              $ref: '#/components/schemas/AMS_Shema_CS_AGG'
      responses:
        '200':
          #  ----- Added code 200  ----------------------------------------
          description: Successfully created a new artist
        '400':
          #  ----- Added error 400  ----------------------------------------
          $ref: '#/components/responses/400Error'
   


# CS_AMS_AID
  /CS_AMS_AID/dagRuns:
    post:
      summary: 'CS AMS AID'
      operationId: CS_AMS_AID
      tags:
        - CS AMS AID
      requestBody:
        required: true
        content:
          application/json:
            schema:
              #  ----- Added schema  ------------------------------------
              $ref: '#/components/schemas/AMS_Shema_CS_AID'
      responses:
        '200':
          #  ----- Added code 200  ----------------------------------------
          description: Successfully created a new artist
        '400':
          #  ----- Added error 400  ----------------------------------------
          $ref: '#/components/responses/400Error'
   


# CS_AMS_AUTOSCALE
  /CS_AMS_AUTOSCALE/dagRuns:
    post:
      summary: 'Add Summary Here'
      operationId: CS_AMS_AUTOSCALE
      tags:
        - CS AMS AUTOSCALE
      requestBody:
        required: true
        content:
          application/json:
            schema:
              #  ----- Added schema  ------------------------------------
              $ref: '#/components/schemas/TO_DO_Shema'
      responses:
        '200':
          #  ----- Added code 200  ----------------------------------------
          description: Successfully created a new artist
        '400':
          #  ----- Added error 400  ----------------------------------------
          $ref: '#/components/responses/400Error'
   


# CS_AMS_CENSUS_STORES
  /CS_AMS_CENSUS_STORES/dagRuns:
    post:
      summary: 'Add Summary Here'
      operationId: CS_AMS_CENSUS_STORES
      tags:
        - CS AMS CENSUS STORES
      requestBody:
        required: true
        content:
          application/json:
            schema:
              #  ----- Added schema  ------------------------------------
              $ref: '#/components/schemas/TO_DO_Shema'
      responses:
        '200':
          #  ----- Added code 200  ----------------------------------------
          description: Successfully created a new artist
        '400':
          #  ----- Added error 400  ----------------------------------------
          $ref: '#/components/responses/400Error'
   


# CS_AMS_CUSTOM_WEEKLY_REFRESH
  /CS_AMS_CUSTOM_WEEKLY_REFRESH/dagRuns:
    post:
      summary: 'Add Summary Here'
      operationId: CS_AMS_CUSTOM_WEEKLY_REFRESH
      tags:
        - CS AMS CUSTOM WEEKLY REFRESH
      requestBody:
        required: true
        content:
          application/json:
            schema:
              #  ----- Added schema  ------------------------------------
              $ref: '#/components/schemas/TO_DO_Shema'
      responses:
        '200':
          #  ----- Added code 200  ----------------------------------------
          description: Successfully created a new artist
        '400':
          #  ----- Added error 400  ----------------------------------------
          $ref: '#/components/responses/400Error'
   


# CS_AMS_EDA_MODEL
  /CS_AMS_EDA_MODEL/dagRuns:
    post:
      summary: 'Add Summary Here'
      operationId: CS_AMS_EDA_MODEL
      tags:
        - CS AMS EDA MODEL
      requestBody:
        required: true
        content:
          application/json:
            schema:
              #  ----- Added schema  ------------------------------------
              $ref: '#/components/schemas/AMS_Shema_CS_EDA_MODEL'
      responses:
        '200':
          #  ----- Added code 200  ----------------------------------------
          description: Successfully created a new artist
        '400':
          #  ----- Added error 400  ----------------------------------------
          $ref: '#/components/responses/400Error'
   

# EDA_MODEL_PARALLEL_SPLITS
  /EDA_MODEL_PARALLEL_SPLITS/dagRuns:
    post:
      summary: 'Add Summary Here'
      operationId: EDA_MODEL_PARALLEL_SPLITS
      tags:
        - EDA MODEL PARALLEL SPLITS
      requestBody:
        required: true
        content:
          application/json:
            schema:
              #  ----- Added schema  ------------------------------------
              $ref: '#/components/schemas/TO_DO_Shema'
      responses:
        '200':
          #  ----- Added code 200  ----------------------------------------
          description: Successfully created a new artist
        '400':
          #  ----- Added error 400  ----------------------------------------
          $ref: '#/components/responses/400Error'
   

# CS_AMS_ITEM_SUMMARY  
  /CS_AMS_ITEM_SUMMARY/dagRuns:
    post:
      summary: 'Add Summary Here'
      operationId: CS_AMS_ITEM_SUMMARY
      tags:
        - CS AMS ITEM SUMMARY
      requestBody:
        required: true
        content:
          application/json:
            schema:
              #  ----- Added schema  ------------------------------------
              $ref: '#/components/schemas/TO_DO_Shema'
      responses:
        '200':
          #  ----- Added code 200  ----------------------------------------
          description: Successfully created a new artist
        '400':
          #  ----- Added error 400  ----------------------------------------
          $ref: '#/components/responses/400Error'
   

# CS_AMS_ITEMAGG  
  /CS_AMS_ITEMAGG/dagRuns:
    post:
      summary: 'Add Summary Here'
      operationId: CS_AMS_ITEMAGG
      tags:
        - CS AMS ITEMAGG
      requestBody:
        required: true
        content:
          application/json:
            schema:
              #  ----- Added schema  ------------------------------------
              $ref: '#/components/schemas/AMS_Shema_itemAgg'
      responses:
        '200':
          #  ----- Added code 200  ----------------------------------------
          description: Successfully created a new artist
        '400':
          #  ----- Added error 400  ----------------------------------------
          $ref: '#/components/responses/400Error'
   

# CS_AMS_MID  
  /CS_AMS_MID/dagRuns:
    post:
      summary: 'Add Summary Here'
      operationId: CS_AMS_MID
      tags:
        - CS AMS MID
      requestBody:
        required: true
        content:
          application/json:
            schema:
              #  ----- Added schema  ------------------------------------
              $ref: '#/components/schemas/AMS_Shema_CS_MID'
      responses:
        '200':
          #  ----- Added code 200  ----------------------------------------
          description: Successfully created a new artist
        '400':
          #  ----- Added error 400  ----------------------------------------
          $ref: '#/components/responses/400Error'
   


# CS_AMS_NONAGG
  /CS_AMS_NONAGG/dagRuns:
    post:
      summary: 'Add Summary Here'
      operationId: CS_AMS_NONAGG
      tags:
        - CS AMS NONAGG
      requestBody:
        required: true
        content:
          application/json:
            schema:
              #  ----- Added schema  ------------------------------------
              $ref: '#/components/schemas/AMS_Shema_CS_NONAGG'
      responses:
        '200':
          #  ----- Added code 200  ----------------------------------------
          description: Successfully created a new artist
        '400':
          #  ----- Added error 400  ----------------------------------------
          $ref: '#/components/responses/400Error'
   

# CS_AMS_POS_SUMMARY
  /CS_AMS_POS_SUMMARY/dagRuns:
    post:
      summary: 'Add Summary Here'
      operationId: CS_AMS_POS_SUMMARY
      tags:
        - CS AMS POS SUMMARY
      requestBody:
        required: true
        content:
          application/json:
            schema:
              #  ----- Added schema  ------------------------------------
              $ref: '#/components/schemas/TO_DO_Shema'
      responses:
        '200':
          #  ----- Added code 200  ----------------------------------------
          description: Successfully created a new artist
        '400':
          #  ----- Added error 400  ----------------------------------------
          $ref: '#/components/responses/400Error'
   

# CS_AMS_PRICE_THRESHOLDS_MODEL
  /CS_AMS_PRICE_THRESHOLDS_MODEL/dagRuns:
    post:
      summary: 'Add Summary Here'
      operationId: CS_AMS_PRICE_THRESHOLDS_MODEL
      tags:
        - CS AMS PRICE THRESHOLDS MODEL
      requestBody:
        required: true
        content:
          application/json:
            schema:
              #  ----- Added schema  ------------------------------------
              $ref: '#/components/schemas/AMS_Shema_CS_PRICE_THRESHOLDS_MODEL'
      responses:
        '200':
          #  ----- Added code 200  ----------------------------------------
          description: Successfully created a new artist
        '400':
          #  ----- Added error 400  ----------------------------------------
          $ref: '#/components/responses/400Error'
   

# CS_AMS_PRODSIM
  /CS_AMS_PRODSIM/dagRuns:
    post:
      summary: 'Add Summary Here'
      operationId: CS_AMS_PRODSIM
      tags:
        - CS AMS PRODSIM
      requestBody:
        required: true
        content:
          application/json:
            schema:
              #  ----- Added schema  ------------------------------------
              $ref: '#/components/schemas/AMS_Shema_CS_PRODSIM'
      responses:
        '200':
          #  ----- Added code 200  ----------------------------------------
          description: Successfully created a new artist
        '400':
          #  ----- Added error 400  ----------------------------------------
          $ref: '#/components/responses/400Error'
   

# CS_AMS_REGULARPRICE
  /CS_AMS_REGULARPRICE/dagRuns:
    post:
      summary: 'Add Summary Here'
      operationId: CS_AMS_REGULARPRICE
      tags:
        - CS AMS REGULARPRICE
      requestBody:
        required: true
        content:
          application/json:
            schema:
              #  ----- Added schema  ------------------------------------
              $ref: '#/components/schemas/AMS_Shema_CS_REGULARPRICE'
      responses:
        '200':
          #  ----- Added code 200  ----------------------------------------
          description: Successfully created a new artist
        '400':
          #  ----- Added error 400  ----------------------------------------
          $ref: '#/components/responses/400Error'
   

# CS_AMS_STOREAGG
  /CS_AMS_STOREAGG/dagRuns:
    post:
      summary: 'Add Summary Here'
      operationId: CS_AMS_STOREAGG
      tags:
        - CS AMS STOREAGG
      requestBody:
        required: true
        content:
          application/json:
            schema:
              #  ----- Added schema  ------------------------------------
              $ref: '#/components/schemas/AMS_Shema_CS_STOREAGG'
      responses:
        '200':
          #  ----- Added code 200  ----------------------------------------
          description: Successfully created a new artist
        '400':
          #  ----- Added error 400  ----------------------------------------
          $ref: '#/components/responses/400Error'
   

# FAIL_JOB
  /FAIL_JOB/dagRuns:
    post:
      summary: 'Add Summary Here'
      operationId: FAIL_JOB
      tags:
        - FAIL JOB
      requestBody:
        required: true
        content:
          application/json:
            schema:
              #  ----- Added schema  ------------------------------------
              $ref: '#/components/schemas/TO_DO_Shema'
      responses:
        '200':
          #  ----- Added code 200  ----------------------------------------
          description: Successfully created a new artist
        '400':
          #  ----- Added error 400  ----------------------------------------
          $ref: '#/components/responses/400Error'
   


# MASTER_DUMMY_PYTHON
  /MASTER_DUMMY_PYTHON/dagRuns:
    post:
      summary: 'Add Summary Here'
      operationId: MASTER_DUMMY_PYTHON
      tags:
        - MASTER DUMMY PYTHON
      requestBody:
        required: true
        content:
          application/json:
            schema:
              #  ----- Added schema  ------------------------------------
              $ref: '#/components/schemas/TO_DO_Shema'
      responses:
        '200':
          #  ----- Added code 200  ----------------------------------------
          description: Successfully created a new artist
        '400':
          #  ----- Added error 400  ----------------------------------------
          $ref: '#/components/responses/400Error'
   

# SUBMIT_JOB
  /SUBMIT_JOB/dagRuns:
    post:
      summary: 'Add Summary Here'
      operationId: SUBMIT_JOB
      tags:
        - SUBMIT JOB
      requestBody:
        required: true
        content:
          application/json:
            schema:
              #  ----- Added schema  ------------------------------------
              $ref: '#/components/schemas/TO_DO_Shema'
      responses:
        '200':
          #  ----- Added code 200  ----------------------------------------
          description: Successfully created a new artist
        '400':
          #  ----- Added error 400  ----------------------------------------
          $ref: '#/components/responses/400Error'
   

# SUBMIT_JOB_PYTHON
  /SUBMIT_JOB_PYTHON/dagRuns:
    post:
      summary: 'Add Summary Here'
      operationId: SUBMIT_JOB_PYTHON
      tags:
        - SUBMIT JOB PYTHON
      requestBody:
        required: true
        content:
          application/json:
            schema:
              #  ----- Added schema  ------------------------------------
              $ref: '#/components/schemas/TO_DO_Shema'
      responses:
        '200':
          #  ----- Added code 200  ----------------------------------------
          description: Successfully created a new artist
        '400':
          #  ----- Added error 400  ----------------------------------------
          $ref: '#/components/responses/400Error'
   

# SUBMIT_JOB_QA_AS 
  /SUBMIT_JOB_QA_AS/dagRuns:
    post:
      summary: 'Add Summary Here'
      operationId: SUBMIT_JOB_QA_AS
      tags:
        - SUBMIT JOB QA AS
      requestBody:
        required: true
        content:
          application/json:
            schema:
              #  ----- Added schema  ------------------------------------
              $ref: '#/components/schemas/TO_DO_Shema'
      responses:
        '200':
          #  ----- Added code 200  ----------------------------------------
          description: Successfully created a new artist
        '400':
          #  ----- Added error 400  ----------------------------------------
          $ref: '#/components/responses/400Error'
   

components:
  securitySchemes:
    BasicAuth:
      type: http
      scheme: basic
  
  schemas:
    AMS_Shema_MASTER_DUMMY:
      type: object
      required:
        - username
        - password
      properties:
        conf:
          type: object
          properties:
            region: 
              type: string
            json:
                type: object
                properties:
                    country: 
                      type: string
                    dimensions:
                      type: array
                      items:
                        type: object
                        properties:
                          product: 
                            type: array
                            items:
                              type: string
                          market: 
                            type: array
                            items:
                              type: string
                          timeperiod:
                            type: array
                            items:
                              type: string
                          facts: 
                            type: array
                            items:
                              type: string
                          promofacts:
                            type: array
                            items:
                              type: string
                    components:
                        type: array  
                        items:
                          type: object
                          properties:
                            Aggregate to ppg:
                              type: array
                              items:
                                type: string
                    exec_id: 
                     type: string
                    call_backurl:
                      type: string
                    publishing_db:
                      type: string
                    model_type: 
                      type: string
      example:
        conf:
          region: US
          json:
            country: US
            dimensions:
            - product: []
              market: []
              timeperiod: []
              facts: []
              promofacts: []
            components:
            - Aggregate to ppg: []
            exec_id: ''
            call_backurl: ''
            publishing_db: ''
            model_type: custom model
            

    TO_DO_Shema:
      type: object
      required:
        - username
        - password
      properties:
        TO_DO:
          type: object
#          properties:
#            region: 
#              type: string
#            json:
#                type: object
      example:
        TO_DO:
          type: object
                
                
                
    AMS_Shema_CS_PRODSIM: # Schema for CS_AMS_PRODSIM
      type: object
    # required:
    #    - username
    #    - password
      properties:
        conf:
          type: object
          properties:
            gen2environment: 
              type: string
            gen2region: 
              type: string
            json:
              type: object
              properties:
                country: 
                  type: string
                execution_id: 
                  type: integer
                env: 
                  type: string
                publishingDb: 
                  type: string
                region: 
                  type: string
                dataSource: 
                  type: string
                extract_execId: 
                  type: integer
          example:
            conf:
              gen2environment: UAT
              gen2region: US
              json:
                country: US
                region: US
                execution_id: 520
                env: cloud_nonprod
                publishingDb: iaap_data_gmp2_us_uat_publish
                dataSource: BDL
                extract_execId: 520

                  
                  
    AMS_Shema_CS_MID: # Schema for CS_AMS_MID
      type: object
    # required:
    #    - username
    #    - password
      properties:
        conf:
          type: object
          properties:
            gen2environment: 
              type: string
            gen2region: 
              type: string
            json:
              type: object
              properties:
                country: 
                  type: string
                execution_id: 
                  type: integer
                from:
                  type: integer
                env: 
                  type: string
                publishingDb: 
                  type: string
                region: 
                  type: string
                dataSource: 
                  type: string
                extract_execId: 
                  type: integer
      example:
        conf:
          gen2environment: UAT
          gen2region: US
          json:
            region: CALATAM
            country: CA
            execution_id: 12824
            from: API
            env: cloud_nonprod
            publishingDb: iaap_data_gmp2_calatam_uat_publish
            dataSource: BDL
            extract_execId: 12824


    AMS_Shema_itemAgg: # Schema for ams_itemAgg TO BE VALIDATED 
      type: object
    # required:
    #    - username
    #    - password
      properties:
        conf:
          type: object
          properties:
            gen2environment: 
              type: string
            gen2region: 
              type: string
            json:
              type: object
              properties:
                country: 
                  type: string
                execution_id: 
                  type: integer
                env: 
                  type: string
                execid_aid: 
                  type: integer
                execid_extracts: 
                  type: integer
                publishingDb: 
                  type: string
                region: 
                  type: string
      example:
        conf:
          gen2environment: UAT
          gen2region: US
          json:
            country: US
            execution_id: 6018
            env: cloud_nonprod
            execid_aid: 6018
            execid_extracts: 6018
            publishingDb: iaap_data_gmp2_us_uat_publish
            region: US


    AMS_Shema_CS_PRICE_THRESHOLDS_MODEL: # Schema for CS_AMS_PRICE_THRESHOLDS_MODEL 
      type: object
    # required:
    #    - username
    #    - password
      properties:
        conf:
          type: object
          properties:
            gen2environment: 
              type: string
            gen2region: 
              type: string
            json:
              type: object
              properties:
                country: 
                  type: string
                execution_id: 
                  type: integer
                env: 
                  type: string
                itemagg_exec_id: 
                  type: integer
                publishingDb: 
                  type: string
                region: 
                  type: string
      example: 
        conf:
          gen2environment: UAT
          gen2region: US
          json:
            country: CA
            region: CALATAM
            env: cloud_nonprod
            itemagg_exec_id: 12824
            execution_id: 12824
            publishingDb: iaap_data_gmp2_calatam_uat_publish


    AMS_Shema_CS_EDA_MODEL: # Schema for CS_AMS_EDA_MODEL 
      type: object
    # required:
    #    - username
    #    - password
      properties:
        conf:
          type: object
          properties:
            gen2environment: 
              type: string
            gen2region: 
              type: string
            json:
              type: object
              properties:
                country: 
                  type: string
                execution_id: 
                  type: integer
                env: 
                  type: string
                execid_extracts: 
                  type: integer
                publishingDb: 
                  type: string
                threshold_exec_id:
                  type: integer
                runSlowMovingAlgorithm:
                  type: string
                storeagg_exec_id:
                  type: integer
                itemagg_exec_id:
                  type: integer
                execid_aid:
                  type: integer
                extracts_exec_id:
                  type: integer
                region: 
                  type: string
                modelType: 
                  type: string
      example: 
        conf:
         gen2environment: UAT
         gen2region: US
         json:
           country: CA
           region: CALATAM
           execution_id: 12824
           env: cloud_nonprod
           extracts_exec_id: 12824
           execid_aid: 12824
           itemagg_exec_id: 12824
           storeagg_exec_id: 12824
           runSlowMovingAlgorithm: N
           threshold_exec_id: 12824
           publishingDb: iaap_data_gmp2_calatam_uat_publish
           modelType: SM



    AMS_Shema_CS_REGULARPRICE: # Schema for CS_AMS_REGULARPRICE 
      type: object
    # required:
    #    - username
    #    - password
      properties:
        conf:
          type: object
          properties:
            gen2environment: 
              type: string
            gen2region: 
              type: string
            json:
              type: object
              properties:
                country: 
                  type: string
                execution_id: 
                  type: integer
                env: 
                  type: string
                execid_extracts: 
                  type: integer
                publishingDb: 
                  type: string
                region: 
                  type: string
                modelType: 
                  type: string
      example:
        conf:
          gen2environment: UAT
          gen2region: US
          json:
            country: CA
            execution_id: 12824
            env: cloud_nonprod
            execid_extracts: 12824
            execid_itemagg: 12824
            publishingDb: iaap_data_gmp2_calatam_uat_publish
            region: CALATAM
            modelType: SM

                  
                  

    AMS_Shema_CS_STOREAGG: # Schema for CS_AMS_STOREAGG
      type: object
    # required:
    #    - username
    #    - password
      properties:
        conf:
          type: object
          properties:
            gen2environment: 
              type: string
            gen2region: 
              type: string
            json:
              type: object
              properties:
                country: 
                  type: string
                execution_id: 
                  type: integer
                env: 
                  type: string
                publishingDb: 
                  type: string
                region: 
                  type: string
                execid_extracts: 
                  type: integer
      example:
        conf:
          gen2environment: UAT
          gen2region: US
          json:
            country: CA
            execution_id: 12824
            env: cloud_nonprod
            execid_extracts: 12824
            publishingDb: iaap_data_gmp2_calatam_uat_publish
            region: CALATAM

                  

    AMS_Shema_CS_NONAGG: # Schema for CS_AMS_NONAGG_UAT
      type: object
    # required:
    #    - username
    #    - password
      properties:
        conf:
          type: object
          properties:
            gen2environment: 
              type: string
            gen2region: 
              type: string
            json:
              type: object
              properties:
                region: 
                  type: string
                country:
                  type: string
                model: 
                  type: string
                end_date: 
                  type: string
                execution_id: 
                  type: integer
                env: 
                  type: string
                destination: 
                  type: string
                delimiter: 
                  type: string
                deliveryLoc: 
                  type: string
                compressFlag: 
                  type: string
                compressFormat: 
                  type: string
                sample_store_ind: 
                  type: string
                dimOnly: 
                  type: string
                auto_flag: 
                  type: string
                dataSource: 
                  type: string
                maskedFlag: 
                  type: string
                publishingDb:
                  type: string
                studySpecification: 
                  type: string
                studyType: 
                  type: string
                fdsId: 
                  type: integer
                phiId: 
                  type: integer
                dimChars:
                  type: array
                  items:
                    properties:
                      productChars:
                        type: array
                        items:
                          type: string
                      marketChars:
                        type: array
                        items:
                          type: string
                      storeChars:
                        type: array
                        items:
                          type: string
                projects:
                  type: array
                  items:
                    properties:
                      market_id:
                        type: string
                      market_id_comp:
                        type: string
                      promotion_type_id:
                        type: string
                      storeFilter: 
                        type: array
                        items:
                          type: string
                      marketFilter: 
                        type: array
                        items:
                          type: string
                      productFilter: 
                        type: array
                        items:
                          type: string
                no_of_weeks:
                  type: integer
                facts:
                  type: array
                  items:
                    properties:
                      fact_table: 
                        type: string
      example:
        conf:
          gen2environment: UAT
          gen2region: US
          json:
            country: CA
            region: CALATAM
            end_date: '2021-05-01'
            execution_id: 12824
            auto_flag: ''
            destination: sasgrid
            delimiter: "|"
            deliveryLoc: "/sastemp_shr/maya9005/test"
            compressFlag: N
            compressFormat: GZIP
            dimOnly: ''
            env: cloud_nonprod
            dataSource: BDL
            maskedFlag: N
            publishingDb: iaap_data_gmp2_calatam_uat_publish
            studySpecification: syndicated
            studyType: model
            fdsId: 0
            phiId: 0
            sample_store_ind: Y
            dimChars:
              productChars:
              - '71459'
              - '77672'
              - '81288'
              - '78165'
              - '1002'
              - '82813'
              - '1011'
              - '36613'
              - '126421'
              - '71798'
              - '47667'
              - '70565'
              - '1003'
              - '70947'
              - '71693'
              - '71451'
              - '82765'
              - '71993'
              - '72016'
              - '71883'
              - '71588'
              - '70823'
              - '71928'
              - '70980'
              - '71651'
              - '36618'
              - '72078'
              - '71396'
              - '71057'
              - '70722'
              - '1318'
              - '82815'
              - '71177'
              - '70613'
              - '71782'
              - '36601'
              - '82767'
              - '82768'
              - '71600'
              - '36619'
              - '70452'
              - '36615'
              - '82808'
              - '82766'
              - '82764'
              - '2132'
              - '14576'
              - '71411'
              - '70961'
              - '71802'
              - '71174'
              - '94692'
              marketChars:
              - NORMS_MARKET
              storeChars:
              - COUNTRY
            projects:
            - market_id: ''
              market_id_comp: ''
              promotion_type_id: '3506'
              storeFilter:
              - key: COUNTRY
                value:
                - CA
                dimension: SYNDICATED_CHAR
              - key: store_id
                value:
                - '102196415,100053594,100046612,102196289,102379315,100010743,100054582'
                dimension: CUSTOM_LIST
              marketFilter:
              - key: NORMS_MARKET
                value:
                - Y
                dimension: SYNDICATED_CHAR
              productFilter:
              - key: PRODUCT_ID
                value:
                - '35104299,36102100'
                dimension: CUSTOM_LIST
              - key: BARCODE
                value:
                - '000018673900043'
                dimension: CUSTOM_LIST
              - key: '1003'
                value:
                - SKIN CARE - CREAM/GEL/LIQUID - MULTI DOSE
                dimension: SYNDICATED_CHAR
            no_of_weeks: 13
            facts:
            - fact_table: RetailTrendPromotion
            - fact_table: LkpPromotionType
            - fact_table: lookupCharName
            - fact_table: Market_Char_Val
            - fact_table: MarketTbl
            - fact_table: PeriodTbl
            - fact_table: ProductCharValue
            - fact_table: ProductTbl
            - fact_table: StoreCharValue
            - fact_table: storeTbl
            - fact_table: RTS
            - fact_table: Market_Proj_Fac
            - fact_table: ProductSizeDetails
            - fact_table: SizeConversionRate
            - fact_table: vef
            - fact_table: store_location
            - fact_table: week_group
            - fact_table: causals_promo_description
            - fact_table: market_channel_mapping

                        
                        
    AMS_Shema_CS_AGG:  # Shema for AMS_CS_AGG
      type: object
        # required:
        #    - username
        #    - password
      properties:
        conf:
          type: object
          properties:
            gen2environment: 
              type: string
            gen2region: 
              type: string
            json:
              type: object
              properties:
                country: 
                  type: string
                end_date: 
                  type: string
                execution_id: 
                  type: integer 
                env: 
                  type: string
                destination: 
                  type: string
                delimiter: 
                  type: string
                deliveryLoc: 
                  type: string
                compressFlag: 
                  type: string
                compressFormat: 
                  type: string
                sample_store_ind:
                  type: string
                dataSource: 
                  type: string
                maskedFlag: 
                  type: string
                publishingDb: 
                  type: string
                studySpecification: 
                  type: string
                studyType: 
                  type: string
                fdsId: 
                  type: integer
                phiId: 
                  type: integer
                dimChars:
                  type: array
                  items:
                    properties:
                      productChars:
                        type: array
                        items:
                          type: string
                      marketChars:
                        type: array
                        items:
                          type: string
                      storeChars:
                        type: array
                        items:
                          type: string
                projects:
                  type: array
                  items:
                    properties:
                      market_id: 
                        type: string
                      market_id_comp: 
                        type: string
                      promotion_type_id: 
                        type: string
                      storeFilter:
                        type: array
                        items:
                          properties:
                            key:
                              type: string
                            value:
                              type: array
                              items:
                                type: string
                            dimension:
                              type: string
                      marketFilter:
                        type: array
                        items:
                          properties:
                            key: 
                              type: string
                            value:
                              type: array
                              items:
                                type: string
                            dimension: 
                              type: string
                marketCharFileName: 
                  type: string
                Custom_Product_Mapping: 
                  type: string
                no_of_weeks: 
                  type: integer
                facts:
                  type: array
                  items:
                    properties:
                      fact_table: 
                        type: string
                region: 
                  type: string
      example:
        conf:
          gen2environment: UAT
          gen2region: US
          json:
            country: US
            end_date: '2021-08-14'
            execution_id: 797
            env: cloud_nonprod
            destination: ''
            delimiter: "|"
            deliveryLoc: "/sastemp_shr/maya9005/test/usnprod"
            compressFlag: Y
            compressFormat: GZIP
            sample_store_ind: Y
            dataSource: BDL
            maskedFlag: N
            publishingDb: iaap_data_gmp2_us_uat_publish
            studySpecification: syndicated
            studyType: model
            fdsId: 0
            phiId: 0
            dimChars:
              productChars: []
              marketChars:
              - ''
              storeChars:
              - ''
            projects:
            - market_id: ''
              market_id_comp: ''
              promotion_type_id: ''
              storeFilter:
              - key: ''
                value:
                - ''
                dimension: ''
              marketFilter:
              - key: ''
                value:
                - ''
                dimension: ''
            marketCharFileName: dbfs:/FileStore/Events_PnP/sethu/aod_extract/markets.csv
            Custom_Product_Mapping: dbfs:/FileStore/Events_PnP/sethu/aod_extract/product_label.csv
            no_of_weeks: 3
            facts:
            - fact_table: aod_extract
            region: US
        

                

    AMS_Shema_CS_AID:
      type: object
      required:
        - username
        - password
      properties:
        conf:
          type: object
          properties:
            gen2environment:
              type: string
            gen2region: 
              type: string
            json:
              type: object
              properties:
                country:
                  type: string
                execution_id:
                  type: integer
                env: 
                  type: string
                publishingDb: 
                  type: string
                dataSource: 
                  type: string
                extract_execId:
                  type: integer
                prod_chars:
                  type: array
                  items:
                    type: string
                settings:
                  type: object
                  properties:
                    inOutWeeks: 
                      type: integer
                    minCount: 
                      type: integer
                    multiPackDetectionChar:
                      type: string
                label:
                  type: object
                  properties:
                    brandLabel: 
                      type: string
                    manufacturerLabel: 
                      type: string
                    categoryLabel: 
                      type: string
      example:
        conf:
          gen2environment: UAT
          gen2region: US
          json:
            country: US
            execution_id: 8013
            env: cloud_nonprod
            publishingDb: iaap_data_gmp2_us_uat_publish
            dataSource: BDL
            extract_execId: 1438
            prod_chars:
            - "#US LOC BRAND OWNER"
            - "#US LOC BRAND"
            settings:
              inOutWeeks: 8
              minCount: 1000
              multiPackDetectionChar: GLOBAL NUMBER IN MULTIPACK - ACTUAL
            label:
              brandLabel: "#US LOC BRAND"
              manufacturerLabel: "#US LOC BRAND OWNER"
              categoryLabel: "#US LOC BC CATEGORY MASTER"



  responses:
    400Error:
      description: Invalid request
      content:
        application/json:
          schema:
            type: object
            properties:
              message:
                type: string
                
    200Success:
      description: Request completed successfylly
      content:
        application/json:
          schema:
            type: object
            properties:
              conf:
                type: object
                properties:
                    json:
                      type: object
                      properties:
                          call_backurl:
                            type: string
                          components:
                            type: array  
                            items:
                              type: object
                              properties:
                                Aggregate to ppg:
                                  type: array
                                  items:
                                    type: string
                          country: 
                            type: string
                          dimensions:
                              type: array
                              items:
                                type: object
                                properties:
                                  facts:
                                    type: array
                                    items:
                                      type: string
                                  market: 
                                    type: array
                                    items:
                                      type: string
                                  product: 
                                    type: array
                                    items:
                                      type: string
                                  promofacts:
                                    type: array
                                    items:
                                      type: string
                                  timeperiod:
                                    type: array
                                    items:
                                      type: string
                          exec_id: 
                            type: string
                          model_type: 
                            type: string
                          publishing_db: 
                            type: string
                    region: 
                      type: string
              dag_id: 
                type: string
              dag_run_id: 
                type: string
              end_date:
                type: string
              execution_date: 
                type: string
              external_trigger: 
                type: boolean
              logical_date: 
                type: string
              start_date:
                type: string
              state: 
                type: string
          
 
              
